/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {

        DownloadManager manager = new DownloadManager();

        System.out.println("Current Thread: " + Thread.currentThread().getName());
        System.out.println();
        System.out.println("Started Downloads !");
        System.out.println();

        // FOr creating 100s of Threads
        List<Thread> threads = new ArrayList<>();

        //Create All Threads
        for(int i =0 ; i < 1000 ;i++)
        {
            Thread thread = new Thread(new DownloadTask("file" + i, manager));
            threads.add(thread);
        }

        //Start all Threads
        for(Thread thread : threads)
        {
            thread.start();
        }

        //Wait for all threads to finish
        for(Thread thread : threads) 
        {
            try{
                thread.join();
            }
            catch (InterruptedException e)
            {
                System.out.println("interrupted");
            }
        }

        System.out.println(manager.getCompletedDownloads());

        // .start() creates own Threads and it runs concurrently
        // .run() makes main create Thread and it runs sequentially rather than
 
        // t[i].join() makes the main thread wait for other threads to finish

    }
}
