/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {

        System.out.println("Current Thread: " + Thread.currentThread().getName());

       Thread t1 = new Thread(new DownloadTask("movie.mp4"));
       Thread t2 = new Thread(new DownloadTask("photo.png"));
       Thread t3 = new Thread(new DownloadTask("document.pdf"));


       // .start() creates own Threads and it runs concurrently
       t1.start();
       t2.start();
       t3.start();

       // .run() makes main create Thread and it runs sequentially rather than concurrently
        //    t1.run();
        //    t2.run();
        //    t3.run();


    }
}
