/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {

        System.out.println("Current Thread: " + Thread.currentThread().getName());

       DownloadTask d1 = new DownloadTask("movie.mp4");
       DownloadTask d2 = new DownloadTask("photo.png");
       DownloadTask d3= new DownloadTask("document.pdf");


       Thread t1 = new Thread(d1);
       Thread t2 = new Thread(d2);
       Thread t3 = new Thread(d3);

       t1.start();
       t2.start();
       t3.start();
    }
}
