/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testDownloadManagerIncrement() {
        DownloadManager manager = new DownloadManager();
        assertEquals(0, manager.getCompletedDownloads());
        manager.incrementCompletedDownloads();
        assertEquals(1, manager.getCompletedDownloads());
    }
}
